// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: UnityAPI.proto

package unity_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName        string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	ParticipantName string `protobuf:"bytes,2,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	Host            bool   `protobuf:"varint,3,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *JoinTokenRequest) Reset() {
	*x = JoinTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UnityAPI_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenRequest) ProtoMessage() {}

func (x *JoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UnityAPI_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenRequest.ProtoReflect.Descriptor instead.
func (*JoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_UnityAPI_proto_rawDescGZIP(), []int{0}
}

func (x *JoinTokenRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *JoinTokenRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *JoinTokenRequest) GetHost() bool {
	if x != nil {
		return x.Host
	}
	return false
}

type JoinTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinToken string `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
}

func (x *JoinTokenResponse) Reset() {
	*x = JoinTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UnityAPI_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTokenResponse) ProtoMessage() {}

func (x *JoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UnityAPI_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTokenResponse.ProtoReflect.Descriptor instead.
func (*JoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_UnityAPI_proto_rawDescGZIP(), []int{1}
}

func (x *JoinTokenResponse) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

type ParticipantMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsHost bool `protobuf:"varint,1,opt,name=isHost,proto3" json:"isHost,omitempty"`
}

func (x *ParticipantMetadata) Reset() {
	*x = ParticipantMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UnityAPI_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantMetadata) ProtoMessage() {}

func (x *ParticipantMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_UnityAPI_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantMetadata.ProtoReflect.Descriptor instead.
func (*ParticipantMetadata) Descriptor() ([]byte, []int) {
	return file_UnityAPI_proto_rawDescGZIP(), []int{2}
}

func (x *ParticipantMetadata) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

var File_UnityAPI_proto protoreflect.FileDescriptor

var file_UnityAPI_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x41, 0x50, 0x49, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x6e, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x22, 0x32, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2d, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x48,
	0x6f, 0x73, 0x74, 0x32, 0x67, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f,
	0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c, 0x5a, 0x3a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6b,
	0x69, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2d,
	0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x7e, 0x2f, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_UnityAPI_proto_rawDescOnce sync.Once
	file_UnityAPI_proto_rawDescData = file_UnityAPI_proto_rawDesc
)

func file_UnityAPI_proto_rawDescGZIP() []byte {
	file_UnityAPI_proto_rawDescOnce.Do(func() {
		file_UnityAPI_proto_rawDescData = protoimpl.X.CompressGZIP(file_UnityAPI_proto_rawDescData)
	})
	return file_UnityAPI_proto_rawDescData
}

var file_UnityAPI_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_UnityAPI_proto_goTypes = []interface{}{
	(*JoinTokenRequest)(nil),    // 0: unity_protocol.JoinTokenRequest
	(*JoinTokenResponse)(nil),   // 1: unity_protocol.JoinTokenResponse
	(*ParticipantMetadata)(nil), // 2: unity_protocol.ParticipantMetadata
}
var file_UnityAPI_proto_depIdxs = []int32{
	0, // 0: unity_protocol.UnityService.RequestJoinToken:input_type -> unity_protocol.JoinTokenRequest
	1, // 1: unity_protocol.UnityService.RequestJoinToken:output_type -> unity_protocol.JoinTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UnityAPI_proto_init() }
func file_UnityAPI_proto_init() {
	if File_UnityAPI_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UnityAPI_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UnityAPI_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UnityAPI_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UnityAPI_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UnityAPI_proto_goTypes,
		DependencyIndexes: file_UnityAPI_proto_depIdxs,
		MessageInfos:      file_UnityAPI_proto_msgTypes,
	}.Build()
	File_UnityAPI_proto = out.File
	file_UnityAPI_proto_rawDesc = nil
	file_UnityAPI_proto_goTypes = nil
	file_UnityAPI_proto_depIdxs = nil
}
