// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UnityAPI.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UnityProtocol {

  /// <summary>Holder for reflection information generated from UnityAPI.proto</summary>
  public static partial class UnityAPIReflection {

    #region Descriptor
    /// <summary>File descriptor for UnityAPI.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityAPIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Vbml0eUFQSS5wcm90bxIOdW5pdHlfcHJvdG9jb2wiTQoQSm9pblRva2Vu",
            "UmVxdWVzdBIRCglyb29tX25hbWUYASABKAkSGAoQcGFydGljaXBhbnRfbmFt",
            "ZRgCIAEoCRIMCgRob3N0GAMgASgIIicKEUpvaW5Ub2tlblJlc3BvbnNlEhIK",
            "CmpvaW5fdG9rZW4YASABKAkiJQoTUGFydGljaXBhbnRNZXRhZGF0YRIOCgZp",
            "c0hvc3QYASABKAgyZwoMVW5pdHlTZXJ2aWNlElcKEFJlcXVlc3RKb2luVG9r",
            "ZW4SIC51bml0eV9wcm90b2NvbC5Kb2luVG9rZW5SZXF1ZXN0GiEudW5pdHlf",
            "cHJvdG9jb2wuSm9pblRva2VuUmVzcG9uc2VCPFo6Z2l0aHViLmNvbS9saXZl",
            "a2l0L2NsaWVudC11bml0eS1kZW1vL1Byb3RvY29sfi91bml0eV9wcm90b2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UnityProtocol.JoinTokenRequest), global::UnityProtocol.JoinTokenRequest.Parser, new[]{ "RoomName", "ParticipantName", "Host" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UnityProtocol.JoinTokenResponse), global::UnityProtocol.JoinTokenResponse.Parser, new[]{ "JoinToken" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UnityProtocol.ParticipantMetadata), global::UnityProtocol.ParticipantMetadata.Parser, new[]{ "IsHost" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class JoinTokenRequest : pb::IMessage<JoinTokenRequest> {
    private static readonly pb::MessageParser<JoinTokenRequest> _parser = new pb::MessageParser<JoinTokenRequest>(() => new JoinTokenRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinTokenRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnityProtocol.UnityAPIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinTokenRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinTokenRequest(JoinTokenRequest other) : this() {
      roomName_ = other.roomName_;
      participantName_ = other.participantName_;
      host_ = other.host_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinTokenRequest Clone() {
      return new JoinTokenRequest(this);
    }

    /// <summary>Field number for the "room_name" field.</summary>
    public const int RoomNameFieldNumber = 1;
    private string roomName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RoomName {
      get { return roomName_; }
      set {
        roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participant_name" field.</summary>
    public const int ParticipantNameFieldNumber = 2;
    private string participantName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ParticipantName {
      get { return participantName_; }
      set {
        participantName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "host" field.</summary>
    public const int HostFieldNumber = 3;
    private bool host_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Host {
      get { return host_; }
      set {
        host_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinTokenRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinTokenRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomName != other.RoomName) return false;
      if (ParticipantName != other.ParticipantName) return false;
      if (Host != other.Host) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomName.Length != 0) hash ^= RoomName.GetHashCode();
      if (ParticipantName.Length != 0) hash ^= ParticipantName.GetHashCode();
      if (Host != false) hash ^= Host.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RoomName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomName);
      }
      if (ParticipantName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantName);
      }
      if (Host != false) {
        output.WriteRawTag(24);
        output.WriteBool(Host);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoomName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
      }
      if (ParticipantName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantName);
      }
      if (Host != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinTokenRequest other) {
      if (other == null) {
        return;
      }
      if (other.RoomName.Length != 0) {
        RoomName = other.RoomName;
      }
      if (other.ParticipantName.Length != 0) {
        ParticipantName = other.ParticipantName;
      }
      if (other.Host != false) {
        Host = other.Host;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RoomName = input.ReadString();
            break;
          }
          case 18: {
            ParticipantName = input.ReadString();
            break;
          }
          case 24: {
            Host = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class JoinTokenResponse : pb::IMessage<JoinTokenResponse> {
    private static readonly pb::MessageParser<JoinTokenResponse> _parser = new pb::MessageParser<JoinTokenResponse>(() => new JoinTokenResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinTokenResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnityProtocol.UnityAPIReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinTokenResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinTokenResponse(JoinTokenResponse other) : this() {
      joinToken_ = other.joinToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinTokenResponse Clone() {
      return new JoinTokenResponse(this);
    }

    /// <summary>Field number for the "join_token" field.</summary>
    public const int JoinTokenFieldNumber = 1;
    private string joinToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JoinToken {
      get { return joinToken_; }
      set {
        joinToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinTokenResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinTokenResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (JoinToken != other.JoinToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (JoinToken.Length != 0) hash ^= JoinToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (JoinToken.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(JoinToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (JoinToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JoinToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinTokenResponse other) {
      if (other == null) {
        return;
      }
      if (other.JoinToken.Length != 0) {
        JoinToken = other.JoinToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            JoinToken = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ParticipantMetadata : pb::IMessage<ParticipantMetadata> {
    private static readonly pb::MessageParser<ParticipantMetadata> _parser = new pb::MessageParser<ParticipantMetadata>(() => new ParticipantMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ParticipantMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnityProtocol.UnityAPIReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParticipantMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParticipantMetadata(ParticipantMetadata other) : this() {
      isHost_ = other.isHost_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParticipantMetadata Clone() {
      return new ParticipantMetadata(this);
    }

    /// <summary>Field number for the "isHost" field.</summary>
    public const int IsHostFieldNumber = 1;
    private bool isHost_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsHost {
      get { return isHost_; }
      set {
        isHost_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ParticipantMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ParticipantMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsHost != other.IsHost) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IsHost != false) hash ^= IsHost.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IsHost != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsHost);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IsHost != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ParticipantMetadata other) {
      if (other == null) {
        return;
      }
      if (other.IsHost != false) {
        IsHost = other.IsHost;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsHost = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
